/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBtn: typeof import('./../shared/components/el/btn.vue')['default']
    ElBtnToggle: typeof import('./../shared/components/el/btnToggle.vue')['default']
    ElCard: typeof import('./../shared/components/el/card.vue')['default']
    ElCheckbox: typeof import('./../shared/components/el/checkbox.vue')['default']
    ElDivider: typeof import('./../shared/components/el/divider.vue')['default']
    ElImg: typeof import('./../shared/components/el/img.vue')['default']
    ElInput: typeof import('./../shared/components/el/input.vue')['default']
    ElInputBox: typeof import('./../shared/components/el/inputBox.vue')['default']
    ElRadio: typeof import('./../shared/components/el/radio.vue')['default']
    ElSectionBlock: typeof import('./../shared/components/el/sectionBlock.vue')['default']
    ElSelect: typeof import('./../shared/components/el/select.vue')['default']
    ElSvgIcon: typeof import('./../shared/components/el/svgIcon.vue')['default']
    ElTag: typeof import('./../shared/components/el/tag.vue')['default']
    WidgetGiscusComment: typeof import('./../shared/components/widget/GiscusComment.vue')['default']
    WidgetPagination: typeof import('./../shared/components/widget/Pagination.vue')['default']
  }
}
