/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBtn: typeof import('./../shared/components/el/Btn.vue')['default']
    ElBtnToggle: typeof import('./../shared/components/el/BtnToggle.vue')['default']
    ElCard: typeof import('./../shared/components/el/Card.vue')['default']
    ElCheckbox: typeof import('./../shared/components/el/Checkbox.vue')['default']
    ElDivider: typeof import('./../shared/components/el/Divider.vue')['default']
    ElImg: typeof import('./../shared/components/el/Img.vue')['default']
    ElInput: typeof import('./../shared/components/el/Input.vue')['default']
    ElInputBox: typeof import('./../shared/components/el/InputBox.vue')['default']
    ElRadio: typeof import('./../shared/components/el/Radio.vue')['default']
    ElSectionBlock: typeof import('./../shared/components/el/SectionBlock.vue')['default']
    ElSelect: typeof import('./../shared/components/el/Select.vue')['default']
    ElSvgIcon: typeof import('./../shared/components/el/SvgIcon.vue')['default']
    ElTag: typeof import('./../shared/components/el/Tag.vue')['default']
    WidgetGiscusComment: typeof import('./../shared/components/widget/GiscusComment.vue')['default']
    WidgetPagination: typeof import('./../shared/components/widget/Pagination.vue')['default']
  }
}
